version: 2

updates:
  - package-ecosystem: npm
    directory: /
    allow:
      - dependency-type: direct
    assignees:
      - vansergen
    versioning-strategy: increase
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: dependencies
      prefix-development: devDependencies

  - package-ecosystem: github-actions
    assignees:
      - vansergen
    labels:
      - dependabot
      - ci
    commit-message:
      prefix: ci
